image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Elasticsearch
    init: |
      docker build -t hyper-elasticsearch .elasticsearch
      docker run -p 9200:9200 -p 9600:9600 --name local-hyper-elasticsearch hyper-elasticsearch
    command: |
      docker start -a local-hyper-elasticsearch

  - name: Set Git Hooks
    init: deno task prepare

ports:
  - port: 9200
    onOpen: ignore
    visibility: public
  - port: 9600
    onOpen: ignore
    visibility: public
  - port: 6363
    onOpen: ignore
    visibility: public
    