image:
  file: .gitpod.Dockerfile
tasks:
  - name: Start Elasticsearch
    init: |
      docker build -t hyper-elasticsearch .elasticsearch
      docker run -p 9200:9200 -p 9600:9600 --name local-hyper-elasticsearch hyper-elasticsearch
    command: |
      docker start -a local-hyper-elasticsearch

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    